name: REST API Validation

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose the Python version you want to use

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have a requirements file

    - name: Run API Validation
      run: python validate_api.py  # Replace with the command to run your Python script

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results  # Change this to the directory where your test results are stored
